name: MySQL Script Executor

# Trigger the workflow on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  execute-sql:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository containing the SQL scripts
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies (mysql-connector-python)
      - name: Install MySQL connector
        run: |
          python -m pip install --upgrade pip
          pip install mysql-connector-python

      # Execute the SQL script using a Python script
      - name: Execute SQL Scripts
        env:
          DB_HOST: ${{ secrets.naitik.mysql.database.azure.com }}
          DB_USER: ${{ secrets.rootdb }}
          DB_PASSWORD: ${{ secrets.qwerty@1234}}
          DB_NAME: ${{ secrets.db1 }}
        run: |
          python pythonscript.py
